import type { Metadata } from "next";
import "../components/styles/globals.css";
import StyledComponentsRegistry from './registry'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StyledComponentsRegistry>
      <html lang="en">
        <body>{children}</body>
      </html>
    </StyledComponentsRegistry>
  );
}
